version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  backend:
    build:  
      context: .
      dockerfile: Dockerfile  
    image: springboot-container:${VERSION}  
    container_name: springboot-container
    ports:
      - "9090:9090"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/erp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:  # Named volume instead of external
