version: "3.8"
services:
  backend:
    build:  # ✅ Dockerfile se build karwao
      context: .
      dockerfile: Dockerfile  # ✅ Dockerfile ka naam specify karo
    image: springboot-container:${VERSION}  # ✅ Local image use karo
    container_name: springboot-container
    ports:
      - "9090:9090"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/erp  # Connect to local MySQL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    external: true  
