apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-service
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30091
